import { useState } from 'react'

const STORAGE_KEY = 'athena_disclosure_v1'

const CONTENT = {
  ja: {
    tab: '日本語',
    eyebrow: 'EU AI法 第50条（EU AI Act Article 50）に基づく開示',
    title: 'AIシステム開示通知',
    sections: [
      {
        heading: 'AIシステムとの対話（第50条第1項）',
        text: 'あなたは人工知能（AI）システムと直接対話しています。このシステムは人間ではなくAIエージェントによって動作します。EU AI Act 第50条第1項は、AIシステムと直接対話する自然人に対し、初回の対話時点でその旨を明確に通知することを義務付けています。',
      },
      {
        heading: 'AI生成コンテンツ（第50条第2項）',
        text: '本システムが生成するテキスト出力（計画、分析、レポートを含む）はAIモデルによって生成されます。これらの出力はAIによって生成されたものであり、人間の著作物ではありません。',
      },
      {
        heading: 'オペレーターの監督権限',
        text: 'AIエージェントの活動はいつでも中断・修正・停止することができます。本システムはオペレーターの指示のもとで動作し、重要な判断においてオペレーターの承認を必要とします。',
      },
      {
        heading: '法的根拠',
        text: 'この通知は、欧州連合規則 2024/1689（EU AI Act）第50条第1項および第5項に基づき提供されます。第5項は、開示が「初回の対話時点までに、明確かつ識別可能な方法で」行われることを義務付けており、本通知はその要件を満たすものです。',
      },
    ],
    checkbox: '上記の内容を理解し、AIシステムと対話していることを認識した上で同意します。',
    accept: '同意して続行する',
  },
  en: {
    tab: 'English',
    eyebrow: 'Disclosure under EU AI Act Article 50',
    title: 'AI System Disclosure',
    sections: [
      {
        heading: 'Interacting with an AI system (Article 50(1))',
        text: 'You are interacting directly with an artificial intelligence system. This system is operated by AI agents, not human operators. Article 50(1) of the EU AI Act requires that natural persons interacting directly with an AI system are informed of this at the time of their first interaction, where it is not otherwise obvious.',
      },
      {
        heading: 'AI-generated content (Article 50(2))',
        text: 'Text outputs produced by this system — including plans, analyses, and reports — are generated by AI models. These outputs are artificially generated and do not constitute human-authored content.',
      },
      {
        heading: 'Operator authority',
        text: 'You may pause, redirect, or stop any AI agent activity at any time. The system operates under your direction and requires your approval at defined decision points.',
      },
      {
        heading: 'Legal basis',
        text: 'This notice fulfils the transparency obligations under Articles 50(1) and 50(5) of Regulation (EU) 2024/1689 (EU AI Act). Article 50(5) requires that this information be provided in a clear and distinguishable manner at the latest at the time of the first interaction, and that it conforms to applicable accessibility requirements.',
      },
    ],
    checkbox: 'I understand and acknowledge that I am interacting with an AI system.',
    accept: 'Accept and continue',
  },
}

export function AcceptanceBanner() {
  const [accepted, setAccepted] = useState(() => !!localStorage.getItem(STORAGE_KEY))
  const [lang, setLang] = useState('ja')
  const [checked, setChecked] = useState(false)

  if (accepted) return null

  const c = CONTENT[lang]

  function handleAccept() {
    if (!checked) return
    localStorage.setItem(STORAGE_KEY, '1')
    setAccepted(true)
  }

  return (
    <div className="banner-overlay">
      <div className="banner-card">

        <div className="banner-lang-tabs">
          {Object.entries(CONTENT).map(([key, val]) => (
            <button
              key={key}
              className={`banner-lang-tab${lang === key ? ' active' : ''}`}
              onClick={() => setLang(key)}
            >
              {val.tab}
            </button>
          ))}
        </div>

        <p className="banner-eyebrow">{c.eyebrow}</p>
        <h1 className="banner-title">{c.title}</h1>

        <div className="banner-body">
          {c.sections.map((s, i) => (
            <div key={i} className="banner-section">
              <h2 className="banner-section-heading">{s.heading}</h2>
              <p className="banner-section-text">{s.text}</p>
            </div>
          ))}
        </div>

        <div className="banner-footer">
          <label className="banner-checkbox-label">
            <input
              type="checkbox"
              checked={checked}
              onChange={e => setChecked(e.target.checked)}
              className="banner-checkbox"
            />
            <span>{c.checkbox}</span>
          </label>
          <button
            className={`banner-accept-btn${checked ? '' : ' disabled'}`}
            onClick={handleAccept}
            disabled={!checked}
          >
            {c.accept}
          </button>
        </div>

      </div>
    </div>
  )
}
