"""Orchestrator: two-phase pipeline entry point.

Phase 1 — Clarification loop (interactive):
  The Orchestrator LLM reads the instructions, may ask the user questions
  via ask_user, or reject the run via reject_run. When satisfied it emits
  an OrchestratorApproval JSON and stops.

Phase 2 — Pipeline execution (deterministic):
  Python takes the approval and drives the committee sequence. No LLM
  decisions happen here — the order is fixed in code.
"""

from __future__ import annotations

import logging
import queue
import sys
from pathlib import Path
from typing import Callable

import yaml
from pubsub import pub

from athena.agent_loop import run_agent
from athena.artifacts import RunLogger, render_plan_report, render_recon_report, render_report, render_retrieval_report
from athena.committees.planning import run_planning_committee
from athena.committees.recon import run_recon_committee
from athena.committees.reporting import run_reporting_committee
from athena.committees.retrieval import run_retrieval_committee
from athena.config import AthenaConfig
from athena.model_backend import BackendFactory, ModelBackend, ToolDefinition, make_backend
from athena.schemas import OrchestratorApproval
from athena.utils import extract_json, new_id

_log = logging.getLogger("athena.orchestrator")

# The orchestrator must only end its turn with the approval JSON; every operator
# message must go through ask_user. Models sometimes break this by answering a
# mid-briefing question in plain text and stopping. When that happens we deliver
# the text to the operator and re-run the briefing with that context. This bounds
# how many such recoveries we attempt before giving up.
_MAX_BRIEFING_ATTEMPTS = 4

_ASK_USER = ToolDefinition(
    name="ask_user",
    description="Ask the user a clarifying question and wait for their answer.",
    parameters={
        "type": "object",
        "properties": {
            "question": {"type": "string", "description": "Question to ask the user"},
        },
        "required": ["question"],
    },
)

_REJECT_RUN = ToolDefinition(
    name="reject_run",
    description=(
        "Refuse the engagement and exit cleanly. Use when instructions are out of scope, "
        "request offensive actions, or cannot be made safe."
    ),
    parameters={
        "type": "object",
        "properties": {
            "reason": {"type": "string", "description": "Clear explanation of the rejection"},
        },
        "required": ["reason"],
    },
)


class RunRejected(Exception):
    """Raised inside the dispatch function when the Orchestrator calls reject_run."""
    def __init__(self, reason: str) -> None:
        self.reason = reason
        super().__init__(reason)


def _load_system(config_path: Path) -> str:
    raw = yaml.safe_load(config_path.read_text())
    if "system" not in raw:
        raise ValueError(f"Agent config {config_path} missing 'system' field")
    return raw["system"]


def run_orchestrator(
    instructions: str,
    config: AthenaConfig,
    _backend_factory: BackendFactory = make_backend,
    ask_user_handler: Callable[[str], str] | None = None,
    run_id: str | None = None,
    leader_queues: dict[str, queue.Queue] | None = None,
    approval_gate_handler: Callable[[], bool] | None = None,
) -> OrchestratorApproval | None:
    """Run the full two-phase pipeline.

    Returns the OrchestratorApproval if the run completed, None if rejected.

    ask_user_handler: when provided, used instead of stdin for orchestrator
      questions. The server passes a handler that fires an SSE event and blocks
      on a threading.Event until the operator replies via POST /chat.

    run_id: pre-generated by the server so the caller knows the ID before
      the pipeline thread starts. The CLI leaves this None (ID auto-generated).

    leader_queues: per-agent queue.Queues for committee leaders, keyed by
      agent_id. The server pre-creates these so operators can inject messages
      mid-run via POST /chat.
    """
    effective_run_id = run_id or new_id()

    orch_cfg = config.orchestrator
    provider = orch_cfg.provider or config.model.provider
    system = _load_system(orch_cfg.config_path)

    # ask_user is available if running interactively OR a handler was injected.
    has_ask_user = sys.stdin.isatty() or ask_user_handler is not None
    tools = [_ASK_USER, _REJECT_RUN] if has_ask_user else [_REJECT_RUN]

    def _ask(question: str) -> str:
        """Deliver a message to the operator and return their reply."""
        if ask_user_handler is not None:
            return ask_user_handler(question)
        # CLI path: handler not injected, send event here and read stdin.
        pub.sendMessage("orchestrator.question", run_id=effective_run_id, question=question)
        print(f"\n[Orchestrator] {question}")
        answer = input("> ").strip()
        pub.sendMessage("orchestrator.answer", run_id=effective_run_id, answer=answer)
        return answer

    def dispatch(tool: str, inp: dict) -> str:
        if tool == "ask_user":
            return _ask(inp["question"])
        if tool == "reject_run":
            raise RunRejected(inp["reason"])
        return f"Unknown tool: {tool!r}"

    # --- Phase 1: clarification loop ---
    # A well-behaved orchestrator only ends its turn with the approval JSON. If it
    # instead ends with plain prose, it answered the operator without using ask_user;
    # rather than crash on extract_json, deliver that prose to the operator, take
    # their reply, and re-run the briefing with the added context. Bounded so a
    # persistently malformed model still terminates.
    _log.info("reading instructions...")
    briefing_input = instructions
    data: dict | None = None
    for _ in range(_MAX_BRIEFING_ATTEMPTS):
        try:
            approval_json = run_agent(
                agent_id="athena.orchestrator",
                system=system,
                initial_message=briefing_input,
                tools=tools,
                tool_dispatch=dispatch,
                backend=_backend_factory(provider, config.model.ollama_base_url),
                model=orch_cfg.model,
                max_iterations=config.max_agent_iterations,
            )
        except RunRejected as exc:
            _log.info("run rejected: %s", exc.reason)
            pub.sendMessage("engagement.rejected", run_id=effective_run_id, reason=exc.reason)
            return None

        try:
            data = extract_json(approval_json)
            break
        except ValueError:
            _log.info("orchestrator ended with prose instead of approval JSON; recovering")
            reply = _ask(approval_json)
            briefing_input = (
                f"{instructions}\n\n"
                "[The pre-engagement briefing is already underway — do NOT repeat your "
                "opening brief. Your previous message to the operator was:\n"
                f"{approval_json}\n\n"
                f"The operator replied: {reply}\n\n"
                "Respond only via ask_user, and output the approval JSON strictly after "
                "the operator types CONFIRM.]"
            )

    if data is None:
        raise RuntimeError(
            f"orchestrator: briefing did not yield an approval after {_MAX_BRIEFING_ATTEMPTS} attempts"
        )

    approval = OrchestratorApproval(
        run_id=effective_run_id,
        target=data["target"],
        notes=data["notes"],
    )
    _log.info("approved — target: %s", approval.target)
    _log.info(approval.notes)

    pub.sendMessage(
        "engagement.started",
        run_id=approval.run_id,
        target=approval.target,
        notes=approval.notes,
    )

    # --- Phase 2: deterministic pipeline ---
    logger = RunLogger(approval.run_id, config.artifacts_dir)
    logger.log("run started")
    logger.write_artifact("approval", approval.model_dump_json(indent=2))

    def _leader_queue(agent_id: str) -> queue.Queue | None:
        return leader_queues.get(agent_id) if leader_queues else None

    logger.log("recon committee summoned")
    pub.sendMessage("committee.started", run_id=approval.run_id, committee="recon")

    recon_artifact = run_recon_committee(
        approval=approval,
        config=config,
        _backend_factory=_backend_factory,
        leader_queue=_leader_queue("athena.recon.leader"),
    )

    pub.sendMessage("committee.completed", run_id=approval.run_id, committee="recon")
    logger.log("recon artifact emitted")
    logger.write_artifact("recon", recon_artifact.model_dump_json(indent=2))
    (logger.run_dir / "recon.md").write_text(render_recon_report(recon_artifact))
    pub.sendMessage(
        "committee.artifact_emitted",
        run_id=approval.run_id,
        committee="recon",
        artifact_path="recon.json",
    )
    logger.log("recon committee spun down")

    logger.log("planning committee summoned")
    pub.sendMessage("committee.started", run_id=approval.run_id, committee="planning")

    plan_artifact = run_planning_committee(
        recon_artifact=recon_artifact,
        config=config,
        _backend_factory=_backend_factory,
        leader_queue=_leader_queue("athena.planning.leader"),
    )

    pub.sendMessage("committee.completed", run_id=approval.run_id, committee="planning")
    logger.log("plan artifact emitted")
    logger.write_artifact("plan", plan_artifact.model_dump_json(indent=2))
    (logger.run_dir / "plan.md").write_text(render_plan_report(plan_artifact))
    pub.sendMessage(
        "committee.artifact_emitted",
        run_id=approval.run_id,
        committee="planning",
        artifact_path="plan.json",
    )
    logger.log("planning committee spun down")

    # Operator approval gate — block until the operator reviews the plan and approves.
    if approval_gate_handler is not None:
        approved = approval_gate_handler()
        if not approved:
            _log.info("retrieval phase rejected by operator at approval gate")
            pub.sendMessage(
                "engagement.rejected",
                run_id=approval.run_id,
                reason="Operator rejected the retrieval phase after plan review.",
            )
            return None
        _log.info("retrieval phase approved by operator")

    logger.log("retrieval committee summoned")
    pub.sendMessage("committee.started", run_id=approval.run_id, committee="retrieval")

    retrieval_artifact = run_retrieval_committee(
        plan_artifact=plan_artifact,
        recon_artifact=recon_artifact,
        config=config,
        _backend_factory=_backend_factory,
        leader_queue=_leader_queue("athena.retrieval.leader"),
    )

    pub.sendMessage("committee.completed", run_id=approval.run_id, committee="retrieval")
    logger.log("retrieval artifact emitted")
    logger.write_artifact("retrieval", retrieval_artifact.model_dump_json(indent=2))
    (logger.run_dir / "retrieval.md").write_text(render_retrieval_report(retrieval_artifact))
    pub.sendMessage(
        "committee.artifact_emitted",
        run_id=approval.run_id,
        committee="retrieval",
        artifact_path="retrieval.json",
    )
    logger.log("retrieval committee spun down")

    logger.log("reporting committee summoned")
    pub.sendMessage("committee.started", run_id=approval.run_id, committee="reporting")

    report_artifact = run_reporting_committee(
        recon_artifact=recon_artifact,
        plan_artifact=plan_artifact,
        retrieval_artifact=retrieval_artifact,
        config=config,
        _backend_factory=_backend_factory,
        leader_queue=_leader_queue("athena.reporting.leader"),
    )

    pub.sendMessage("committee.completed", run_id=approval.run_id, committee="reporting")
    logger.log("report artifact emitted")
    logger.write_artifact("report", report_artifact.model_dump_json(indent=2))
    (logger.run_dir / "report.md").write_text(render_report(report_artifact))
    pub.sendMessage(
        "committee.artifact_emitted",
        run_id=approval.run_id,
        committee="reporting",
        artifact_path="report.json",
    )
    logger.log("reporting committee spun down")
    logger.log("run completed")

    pub.sendMessage("engagement.completed", run_id=approval.run_id)

    return approval
